export const sublevel02 = [
// 01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
//           10        20        30        40        50        60        70        80        90        100       110       120       130       140       150       160       170       180       190       200       210       220       230       240       250       260       270       280       290       300       310       320       330       340       350       360       370       380       390       400
  'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx F  xxxxxx',
  'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx L  xxxxxx',
  'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxx',
  'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxx',
  'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxx',
  'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxx',
  'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxx',
  '                                                                                                     x',
  '                                                                                                     x',
  '                   #                                                                                 x',
  '                                                                                                     x',
  '                                                                           #                         x',
  '                                                                                                     x',
  '                   #                                                                                 x',
  '                                                                                                     x',
  '                   #                                                       #                         x',
  '                                                                                                     x',
  '                                                                                                     x',
  '                   #                                                       #                         x',
  '                                                                                                     x',
  '                                                                           #                         x',
  '                                                                                                     x',
  '                                                                                                     x',
  '                   #                                                       #                         x',
  '                                                                                                     x',
  '                                                                                                     x',
  '                                                                                                     x',
  '                   #                                                                                 x',
  '                                                                           #                         x',
  '                                                                                                     x',
  '       L                                                                                             x',
  '                                                                           #                         x',
  '                   #                                                                                 x',
  '                                                                                                     x',
  '                                                                                                     x',
  'wwwwww    wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
  '                                                                            x                        x',
  '                                                                            x                        x',
  '                                                                            x                        x',
  '                         #                                                  x                        x',
  '                                                                            x                        x',
  '                                                                            x                        x',
  '                         #                                                  x                        x',
  '                                                                            x                        x',
  '                         #                                                  x                        x',
  '                                                                            x                        x',
  '                                                                            x                        x',
  '                                                                            x                        x',
  '                         #                                                  x                        x',
  '                                                                            x                        x',
  '                                                                            x                        x',
  '                         #                                                  x                        x',
  '                                                                            x                        x',
  '                                                                            x                        x',
  '                                                                            x                        x',
  '                                                                                                     x',
  '                         #                                                                           x',
  '                                                                                                     x',
  '                                                                                                     x',
  '                                                                                             L       x',
  '                                                                                                     x',
  '                         #                                                                           x',
  '                                                                                                     x',
  '                                                                                                     x',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww    wwwwwx',
  '                                                                                                     x',
  '                                                                                                     x',
  '                                       #                                                             x',
  '                                                                #                                    x',
  '                                                                                                     x',
  '                                                                #                                    x',
  '                                       #                                                             x',
  '                                                                                                     x',
  '                                                                #                                    x',
  '                                                                                                     x',
  '                                       #                                                             x',
  '                                                                #                                    x',
  '                                                                                                     x',
  '                                       #                                                             x',
  '                                                                                                     x',
  '                                                                                                     x',
  '                                                                                                     x',
  '                                                                #                                    x',
  '                                                                                                     x',
  '                                                                #                                    x',
  '                                       #                                                             x',
  '                                                                                                     x',
  '                                                                                                     x',
  '       L                                                                                             x',
  '                                       #                                                             x',
  '                                                                                                     x',
  '                                                                #                                    x',
  '                                                                                                     x',
  'wwwwww    wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
  '                            x                                              #                         x',
  '                         #  x                                  #                                     x',
  '                            x                                                                        x',
  '                   #        x                                              #                         x',
  '                            x                                                                        x',
  '                            x                                  #                                     x',
  '                            x                                                                        x',
  '                            x                                  #                                     x',
  '                   #        x                                                                        x',
  '                            x                                                                        x',
  '                         #  x                                                                        x',
  '                            x                                              #                         x',
  '                            x                                  #                                     x',
  '                            x                                              #                         x',
  '               #         #  x                                                                        x',
  '                   #        x                                                                        x',
  '                            x                                                                        x',
  '                            x                                              #                         x',
  '                            x                                                                        x',
  '                            x                                  #                                     x',
  '               #         #                                                                           x',
  '                   #                                                                                 x',
  '                                                                                                     x',
  '               #                                                                             L       x',
  '                                                               #                                     x',
  '                                                                                                     x',
  '               #         #                                                 #                         x',
  '                                                                                                     x',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww    wwwwwx',
  '                                                                                                     x',
  '                                       #                                                             x',
  '                                                                                                     x',
  '                                       #                        #                                    x',
  '                                                                        #                            x',
  '                                                                                                     x',
  '                                                                                                     x',
  '                                                                                                     x',
  '                                                                #                                    x',
  '                                       #                                                             x',
  '                                                                #                                    x',
  '                                                                                                     x',
  '                                       #                                                             x',
  '                                                                #                                    x',
  '                                       #                                                             x',
  '                                                                                                     x',
  '                                                                #                  %                 x',
  '                   %                                                                                 x',
  '      @                                              %                  #                            x',
  '                                       #      %                                                      x',
  '                                                                                      p              x',
  '                                                                                                     x',
  '                                       #                        #       #                            x',
  '                                                                                                     x',
  '                                                                #                                    x',
  '                                       #                                                             x',
  '                                                                                                     x',
  '                                                                                                     x',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
// 01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
//           10        20        30        40        50        60        70        80        90        100       110       120       130       140       150       160       170       180       190       200       210       220       230       240       250       260       270       280       290       300       310       320       330       340       350       360       370       380       390       400
]
